# Generated by Django 3.0.6 on 2020-06-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text="\n    Designates whether this user account should be considered active.<br/>\n    <strong>NOTE:</strong> Recommended that you set this flag to False instead of deleting accounts; \n    that way, if any applications store foreign keys to users, the foreign keys won’t break.'\n  "),
        ),
    ]
