# Generated by Django 3.0.6 on 2020-06-04 04:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200602_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='discount_ratio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='\n    Designates whether this user can access the admin site.\n  ', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='\n    Designates whether this user account should be considered active.<br/>\n    <strong>NOTE:</strong> Recommended that you set this flag to False instead of deleting accounts; \n    that way, if any applications store foreign keys to users, the foreign keys won’t break.\n  '),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='\n    Designates whether this user can access the admin site.\n  '),
        ),
    ]
