# Generated by Django 3.0.8 on 2020-07-16 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200709_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text='\n    Tax applied to orders (defaults to <strong>0.13</strong>)\n  ', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Tax'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='discount_ratio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='\n    Discount ratio applied to orders\n  ', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Discount'),
        ),
    ]
