# Generated by Django 3.0.8 on 2020-07-22 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200722_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='\n    • Discount applied to orders (before tax)<br/>\n    • Must be a number from 0.00 to 100.00 (up to 2 decimal places)\n  ', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Discount (%)'),
        ),
    ]
