# Generated by Django 3.0.8 on 2020-08-27 09:23

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200722_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='America/Toronto'),
        ),
    ]
