# Generated by Django 3.0.8 on 2020-08-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200828_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address_2',
            field=models.CharField(blank=True, help_text='\n    Apartment, suite, unit, building, floor, etc.\n  ', max_length=30, verbose_name='Address Line 2 (optional)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(help_text='\n    Street and number, P.O. box, c/o.\n  ', max_length=30, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=30, verbose_name='Province'),
        ),
    ]
