# Generated by Django 3.0.8 on 2020-10-07 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200828_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': '👤 User', 'verbose_name_plural': '👤 Users'},
        ),
    ]
