# Generated by Django 3.0.8 on 2020-10-09 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20201007_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='business_phone',
            field=models.CharField(max_length=30, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(max_length=30, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(max_length=50, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.MinLengthValidator(15)], verbose_name='GST/HST Number (optional)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(max_length=30),
        ),
    ]
