# Generated by Django 3.0.8 on 2020-10-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20201009_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country_iso',
            field=models.CharField(choices=[('CAN', 'Canada')], default='CAN', max_length=3, verbose_name='Country'),
        ),
    ]
