# Generated by Django 3.0.6 on 2020-06-02 08:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True, verbose_name='Date Created (UTC)')),
                ('status', models.IntegerField(choices=[(0, 'Current'), (1, 'In Progress'), (2, 'Cancelled'), (3, 'Fulfilled')], help_text="\n    <br/>\n    A Cart can be in 1 of 4 states:<br/>\n    1. <strong>Current</strong> - The currently open cart (each user can only have 1 cart in this state)<br/>\n    2. <strong>In progress</strong> - Cart has been submitted but not yet fulfilled nor cancelled<br/>\n    3. <strong>Cancelled</strong> - Cart can no longer be fulfilled<br/>\n    4. <strong>Fulfilled</strong> - Items have been delivered to client and payment has been received<br/>\n    <br/>\n    <strong>NOTE: </strong>A Cart's status must only ever progress forwards\n    ")),
                ('discount_ratio_applied', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
                ('width', models.CharField(blank=True, max_length=30)),
                ('aspect_ratio', models.CharField(blank=True, max_length=30)),
                ('rim_size', models.CharField(blank=True, max_length=30)),
                ('season', models.CharField(blank=True, max_length=30)),
                ('pattern', models.CharField(blank=True, max_length=30)),
                ('loads', models.CharField(blank=True, max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Price ($)')),
                ('image', models.CharField(blank=True, max_length=200, verbose_name='Tire photo URL')),
                ('current_quantity', models.PositiveIntegerField(default=0)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('sold', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CartDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Cart')),
                ('tire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Tire')),
            ],
        ),
    ]
