# Generated by Django 3.0.6 on 2020-06-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Price ($)'),
        ),
    ]
