# Generated by Django 3.0.6 on 2020-06-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200602_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.IntegerField(choices=[(0, 'Current'), (1, 'In Progress'), (2, 'Cancelled'), (3, 'Fulfilled')], help_text="\n    <br/>\n    A Cart can be in 1 of 4 states:<br/>\n    1. <strong>Current</strong> - The currently open cart (each user can only have 1 cart in this state)<br/>\n    2. <strong>In progress</strong> - Cart has been submitted but not yet fulfilled nor cancelled<br/>\n    3. <strong>Cancelled</strong> - Cart can no longer be fulfilled<br/>\n    4. <strong>Fulfilled</strong> - Items have been delivered to client and payment has been received<br/>\n    <br/>\n    <strong>NOTE: </strong>A Cart's status must only ever progress forwards\n  "),
        ),
    ]
