# Generated by Django 3.0.6 on 2020-06-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200602_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetail',
            name='price_each',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Price ($)'),
        ),
    ]
