# Generated by Django 3.0.6 on 2020-06-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_cartdetail_price_each'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetail',
            name='price_each',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price per item ($)'),
        ),
    ]
