# Generated by Django 3.0.6 on 2020-06-03 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20200603_0640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartdetail',
            options={'verbose_name': 'Cart Item'},
        ),
    ]
