# Generated by Django 3.0.6 on 2020-06-03 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20200603_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tire',
            name='total_quantity',
        ),
    ]
