# Generated by Django 3.0.6 on 2020-06-04 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_remove_tire_total_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tire',
            old_name='loads',
            new_name='load',
        ),
    ]
