# Generated by Django 3.0.6 on 2020-06-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20200604_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Sale Price ($)'),
        ),
    ]
