# Generated by Django 3.0.6 on 2020-06-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20200629_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Fulfilled (UTC)'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date_ordered',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Ordered (UTC)'),
        ),
    ]
