# Generated by Django 3.0.6 on 2020-06-29 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20200629_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='date_ordered',
            new_name='ordered_at',
        ),
    ]
