# Generated by Django 3.0.6 on 2020-06-30 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_auto_20200629_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='fulfilled_at',
            new_name='cancelled_or_fulfilled_at',
        ),
    ]
