# Generated by Django 3.0.6 on 2020-06-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_auto_20200630_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cancelled_or_fulfilled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Cancelled/Fulfilled (UTC)'),
        ),
    ]
