# Generated by Django 3.0.6 on 2020-07-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_auto_20200630_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cancelled_or_fulfilled_at',
        ),
        migrations.AddField(
            model_name='cart',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Fulfilled/Cancelled/Abandoned (UTC)'),
        ),
    ]
