# Generated by Django 3.0.6 on 2020-07-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_auto_20200701_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='\n    Date when the cart was last marked as <strong>Fulfilled</strong>, <strong>Cancelled</strong>, or <strong>Abandoned</strong>\n  ', null=True, verbose_name='Date Closed (UTC)'),
        ),
    ]
