# Generated by Django 3.0.8 on 2020-07-17 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_cart_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='tax',
            new_name='tax_applied',
        ),
    ]
