# Generated by Django 3.0.8 on 2020-07-17 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_auto_20200717_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='tax_applied',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='\n    Tax applied to orders (defaults to <strong>0.13</strong>)\n  ', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
