# Generated by Django 3.0.8 on 2020-07-21 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0035_auto_20200721_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='discount_ratio_applied',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="\n    • Must be a number from 0.00 to 1.00 (up to 2 decimal places)<br/>\n    • Defaults to using the User's discount ratio<br/>\n  ", max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='cart',
            name='tax_applied',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="\n    • Must be a number from 0.00 to 1.00 (up to 2 decimal places)<br/>\n    • Defaults to using the User's tax value<br/>\n  ", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
