# Generated by Django 3.0.8 on 2020-07-22 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0037_auto_20200722_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='discount_percent_applied',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="\n    Defaults to using the User's discount percent<br/>\n  ", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Discount (%)'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='tax_percent_applied',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="\n    Defaults to using the User's tax percent<br/>\n  ", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tax (%)'),
        ),
    ]
