# Generated by Django 3.0.8 on 2020-07-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0040_auto_20200722_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordershipping',
            old_name='Cart',
            new_name='cart',
        ),
    ]
