# Generated by Django 3.0.8 on 2020-07-31 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0041_auto_20200723_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershipping',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Cart'),
        ),
        migrations.AlterModelOptions(
            name='ordershipping',
            options={'verbose_name': 'Shipping Info', 'verbose_name_plural': 'Shipping Info'},
        ),
        migrations.AddField(
            model_name='ordershipping',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordershipping',
            name='address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ordershipping',
            name='city',
            field=models.CharField(max_length=30),
        ),
    ]
