# Generated by Django 3.0.8 on 2020-08-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0043_auto_20200812_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='\n    Date when the cart was last marked as <strong>Fulfilled</strong>, <strong>Cancelled</strong>, or <strong>Abandoned</strong>\n  ', null=True, verbose_name='Date Closed'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='ordered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Ordered'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='cartdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='cartdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
    ]
