# Generated by Django 3.0.8 on 2020-08-28 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0044_auto_20200827_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordershipping',
            name='hst_number',
        ),
        migrations.AddField(
            model_name='ordershipping',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.MinLengthValidator(15)], verbose_name='GST/HST #'),
        ),
    ]
