# Generated by Django 3.0.8 on 2020-09-17 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0048_auto_20200901_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Tread Category',
                'verbose_name_plural': 'Tread Categories',
            },
        ),
        migrations.RemoveField(
            model_name='tire',
            name='image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=200, verbose_name='Tire photo URL')),
                ('tread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Tread', verbose_name='Tread Category')),
            ],
        ),
        migrations.AddField(
            model_name='tire',
            name='tread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Tread', verbose_name='Tread Category'),
        ),
    ]
