# Generated by Django 3.0.8 on 2020-09-17 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0049_auto_20200917_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='url',
        ),
    ]
