# Generated by Django 3.0.8 on 2020-09-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0050_auto_20200917_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='load_speed',
            field=models.CharField(blank=True, max_length=30, verbose_name='Load Index/Speed Rating'),
        ),
    ]
