# Generated by Django 3.0.8 on 2020-09-18 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0051_auto_20200918_0422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tire',
            old_name='season',
            new_name='tire_type',
        ),
    ]
