# Generated by Django 3.0.8 on 2020-09-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0052_auto_20200918_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tire',
            name='name',
        ),
        migrations.AlterField(
            model_name='tire',
            name='tire_type',
            field=models.CharField(blank=True, max_length=30, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='tire',
            name='year',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
