# Generated by Django 3.0.8 on 2020-09-23 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0054_inventory_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdetail',
            name='tire',
        ),
        migrations.AddField(
            model_name='cartdetail',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tire',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Product'),
            preserve_default=False,
        ),
    ]
