# Generated by Django 3.0.8 on 2020-09-29 01:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0054_inventory_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('quantity_change_type', models.CharField(choices=[('➕ Increase stock', (('stock received', '🚚 Stock received'),)), ('➖ Decrease stock', (('sold', '💰 \u200dSold'), ('lost', '🤷\u200d♂️ Lost'), ('other', '❓ Other')))], default='stock received', max_length=30, verbose_name='Increase/Decrease Stock')),
                ('quantity_change_value', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
            },
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='product',
        ),
        migrations.RemoveConstraint(
            model_name='cartdetail',
            name='unique_tire_per_cart',
        ),
        migrations.RemoveField(
            model_name='cartdetail',
            name='tire',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='current_quantity',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='sold',
        ),
        migrations.AddField(
            model_name='cartdetail',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tire',
            name='date_effective',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Date Effective'),
        ),
        migrations.AddField(
            model_name='tire',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='\n    When marked as archived ✔, customers will be unable to view and order this product\n  ', verbose_name='Archived'),
        ),
        migrations.AddConstraint(
            model_name='cartdetail',
            constraint=models.UniqueConstraint(fields=('cart', 'product'), name='unique_product_per_cart'),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Product'),
        ),
    ]
