# Generated by Django 3.0.8 on 2020-09-29 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0055_auto_20200929_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetail',
            name='date_relevant',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Date Effective'),
        ),
    ]
