# Generated by Django 3.0.8 on 2020-09-23 06:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0055_auto_20200923_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='effective_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Date Effective'),
        ),
    ]
