# Generated by Django 3.0.8 on 2020-09-23 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0056_tire_effective_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tire',
            old_name='effective_date',
            new_name='date_effective',
        ),
    ]
