# Generated by Django 3.0.8 on 2020-09-30 00:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0056_cartdetail_date_relevant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetail',
            name='date_relevant',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Date Relevant'),
        ),
    ]
