# Generated by Django 3.0.8 on 2020-09-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0057_auto_20200923_0659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventory Management', 'verbose_name_plural': 'Inventory Management'},
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='quantity_update',
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity_change_type',
            field=models.IntegerField(choices=[(1, 'Increase'), (-1, 'Decrease'), (-2, 'Other Decrease')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity_change_value',
            field=models.IntegerField(default=0),
        ),
    ]
