# Generated by Django 3.0.8 on 2020-09-30 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0057_auto_20200930_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='inherits_from',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inherits_tire_set', to='main_app.Tire'),
        ),
        migrations.AddField(
            model_name='tire',
            name='updated_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_tire_set', to='main_app.Tire'),
        ),
    ]
