# Generated by Django 3.0.8 on 2020-09-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0058_auto_20200924_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity_change_type',
            field=models.CharField(choices=[('➕ Increase stock', (('INCREASE', '🚚Shipment received'),)), ('➖ Decrease stock', (('DECREASE', '💰 Sold'), ('OTHER_DECREASE', '❓ Damaged, lost, etc.')))], max_length=30),
        ),
    ]
