# Generated by Django 3.0.8 on 2020-09-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0059_auto_20200924_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventory'},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity_change_type',
            field=models.CharField(choices=[('➕ Increase stock', (('inventory received', '🚚 Inventory received'),)), ('➖ Decrease stock', (('sold', '💰 Sold'), ('damaged, lost, etc.', '❓ Damaged, lost, etc.')))], max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='\n    When marked as archived ✔, customers will be unable to view and order this product\n  ', verbose_name='Archived'),
        ),
    ]
