# Generated by Django 3.0.8 on 2020-09-27 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0060_auto_20200926_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tire',
            name='current_quantity',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='sold',
        ),
    ]
