# Generated by Django 3.0.8 on 2020-09-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0061_auto_20200927_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity_change_type',
            field=models.CharField(choices=[('➕ Increase stock', (('inventory received', '🚚 Inventory received'),)), ('➖ Decrease stock', (('lost', '🤷\u200d♂️ Lost'), ('other', '❓ Other')))], default='inventory received', max_length=30),
        ),
    ]
