# Generated by Django 3.0.8 on 2020-10-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0061_remove_cartdetail_date_relevant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity_change_type',
            field=models.CharField(choices=[('➕ Increase stock', (('stock received', '🚚 Stock received'),)), ('➖ Decrease stock', (('sold', '💰 \u200dSold offline'), ('shrink', '🤷\u200d♂️ Lost, damaged, administrative error, etc.')))], default='stock received', max_length=30, verbose_name='Increase/Decrease Stock'),
        ),
    ]
