# Generated by Django 3.0.8 on 2020-09-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0062_auto_20200927_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity_change_value',
            field=models.PositiveIntegerField(),
        ),
    ]
