# Generated by Django 3.0.8 on 2020-09-27 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0064_auto_20200927_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity_change_value',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
