# Generated by Django 3.0.8 on 2020-09-27 14:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0065_auto_20200927_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('quantity_change_type', models.CharField(choices=[('➕ Increase stock', (('stock received', '🚚 Stock received'),)), ('➖ Decrease stock', (('lost', '🤷\u200d♂️ Lost'), ('other', '❓ Other')))], default='stock received', max_length=30)),
                ('quantity_change_value', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Product')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
            },
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
