# Generated by Django 3.0.8 on 2020-10-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0065_auto_20201007_0213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tire',
            options={'verbose_name': '📜 Tire Details', 'verbose_name_plural': '📜 Tire Details'},
        ),
        migrations.AddField(
            model_name='tire',
            name='use_sale_price',
            field=models.BooleanField(default=False, help_text='\n    When checked ✔, will use the sale price instead of the regular price\n  ', verbose_name='Use sale price'),
        ),
    ]
