# Generated by Django 3.0.8 on 2020-10-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0066_auto_20201008_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='use_sale_price',
            field=models.BooleanField(default=False, help_text='\n    When checked ✔, will use the sale price instead of the regular price\n  ', verbose_name='On sale'),
        ),
    ]
