# Generated by Django 3.0.8 on 2020-09-28 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0067_auto_20200927_1558'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartdetail',
            name='unique_tire_per_cart',
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity_change_type',
            field=models.CharField(choices=[('➕ Increase stock', (('stock received', '🚚 Stock received'),)), ('➖ Decrease stock', (('sold', '💰 \u200dSold'), ('lost', '🤷\u200d♂️ Lost'), ('other', '❓ Other')))], default='stock received', max_length=30, verbose_name='Increase/Decrease Stock'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity_change_value',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity'),
        ),
        migrations.AddConstraint(
            model_name='cartdetail',
            constraint=models.UniqueConstraint(fields=('cart', 'product'), name='unique_product_per_cart'),
        ),
    ]
